//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432
{
    using System;
    using System.Collections.Generic;
    using Template4432.Models;

    public partial class Client
    {
        public string FIO { get; set; }
        public int UserId { get; set; }
        public string BirthDate { get; set; }
        public int Index { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int House { get; set; }
        public int Apartment { get; set; }
        public string Email { get; set; }
        public static Client MakeClient(JSONClient client)
        {
            return new Client()
            {
                FIO = client.FIO,
                UserId = Convert.ToInt32(client.UserId),
                BirthDate = client.BirthDate,
                Index = Convert.ToInt32(client.Index),
                City = client.City,
                Street = client.Street,
                House = client.House,
                Apartment = client.Apartment,
                Email = client.Email
            };
        }
    }
}
