//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class data
    {
        [JsonPropertyName("IdServices")]
        public int id { get; set; }

        [JsonPropertyName("NameServices")]
        public string name_service { get; set; }

        [JsonPropertyName("TypeOfService")]
        public string kind_service { get; set; }

        [JsonPropertyName("CodeService")]
        public string id_service { get; set; }

        [JsonPropertyName("Cost")]
        public Nullable<int> cost { get; set; }
    }
}
