//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        public int id { get; set; }
        public string name_service { get; set; }
        public string kind_service { get; set; }
        public string id_service { get; set; }
        public Nullable<int> cost { get; set; }
    }
}
