//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public int ClientCode { get; set; }
        public string Services { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string RentTime { get; set; }
    }
}
