//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class OrderSet
    {
        [JsonIgnore]
        public int ID { get; set; }
        [JsonPropertyName("CodeOrder")]
        public string Code { get; set; }
        [JsonPropertyName("CreateDate")]
        public string Date { get; set; }
        [JsonPropertyName("CreateTime")]
        public string Time { get; set; }
        [JsonPropertyName("CodeClient")]
        public string ClientCode { get; set; }
        public string Services { get; set; }
        public string Status { get; set; }
        [JsonPropertyName("ClosedDate")]
        public string ClosingDate { get; set; }
        [JsonPropertyName("ProkatTime")]
        public string RentTime { get; set; }
    }
}
