//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int id { get; set; }
        public string OrderCode { get; set; }
        public string CreatingDate { get; set; }
        public string Time { get; set; }
        public string ClientCode { get; set; }
        public string Services { get; set; }
        public string Status { get; set; }
        public string DateOfClosing { get; set; }
        public string RentTime { get; set; }
    }
}
