//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableIsrpo3
    {
        public int Id { get; set; }
        public string Position { get; set; }
        public string FullName { get; set; }
        public string Log { get; set; }
        public string Password { get; set; }
    }
}
