//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableIsrpo2
    {
        public int id { get; set; }
        public string role_person { get; set; }
        public string fullName { get; set; }
        public string loginPerson { get; set; }
        public string passwordPerson { get; set; }
    }
}
