//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int WorkerID { get; set; }
        public string Post { get; set; }
        public string Full_name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Last_authorization { get; set; }
        public string Type_authorization { get; set; }
    }
}
