//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int ID { get; set; }
        public int Kod_zakaza { get; set; }
        public System.DateTime Data_zakaza { get; set; }
        public System.TimeSpan Vremya { get; set; }
        public int Kod_klienta { get; set; }
        public string Uslugi { get; set; }
        public string Status { get; set; }
        public System.DateTime Data_zakriritiya { get; set; }
        public string Vremya_prokata { get; set; }
    }
}
