//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class Zakaz
    {
        [JsonPropertyName("Id")]
        public int ID { get; set; }
        [JsonPropertyName("CodeOrder")]
        public string Kod_zakaza { get; set; }
        [JsonPropertyName("CreateDate")]
        public string Data_zakaza { get; set; }
        [JsonPropertyName("CreateTime")]
        public string Vremya { get; set; }
        [JsonPropertyName("CodeClient")]
        public string Kod_klienta { get; set; }
        [JsonPropertyName("Services")]
        public string Uslugi { get; set; }
        [JsonPropertyName("Status")]
        public string Status { get; set; }
        [JsonPropertyName("CloseDate")]
        public string Data_zakritiya { get; set; }
        [JsonPropertyName("ProkatTime")]
        public string Vremya_prokata { get; set; }
    }
}
