//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4432._4432_Valiakhmetov_lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public string fio { get; set; }
        public string client_code { get; set; }
        public string birthday { get; set; }
        public string index { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string house_num { get; set; }
        public string flat_num { get; set; }
        public string mail { get; set; }
        public int client_id { get; set; }
    }
}
